name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: |
          mvn test | tee mvn_output.log
          echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
          grep -A 10 '\[INFO\] Results:' mvn_output.log >> $GITHUB_STEP_SUMMARY
