name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests with Maven and collect results
        shell: bash
        run: |
          mvn test 2>&1 | tee mvn_output.log
          MAVEN_EXIT_CODE=${PIPESTATUS[0]}
      
          echo "## 🧪 Test Summary" >> $GITHUB_STEP_SUMMARY
          grep -A 20 '\[INFO\] Results:' mvn_output.log >> $GITHUB_STEP_SUMMARY || echo "No results found" >> $GITHUB_STEP_SUMMARY
      
          exit $MAVEN_EXIT_CODE
